### ISSUE TITLE
A case study in large maps

### ISSUE THREAD

**Issue by dopeghoti** [spoutn1k/mcmap#3]
The capabilities of this program are astounding.

I've been taking daily images of my server's map since September. Recently, some folks have decided to go on walkabout, and the images are still rendering (and rather quickly, too!). They have become large. Quite large.

The most recent daytime image is 142MB in size. That's not the map; that's the image. After being processed by pngcrush.

The resultant monstrosity is so large that it will not open in Firefox, Opera, Safari, or Chrome. But it will open in the GIMP if you have 10GB to let the program swap out to.

mcmap is generating an image measuring in at 48842 × 19434 pixels. At 72 DPI, it would, if printed, be 678.361 × 269.917 inches, or 56 feet, 6 inches, by 22 feet, 5 inches.

This is an extremely robust program. I am impressed. I'd offer to share the image, but I don't think any image hosts will allow such a behemoth.

**Comment by ghost** [comment]
I would have to agree with dopeghoti''s sentiments.

When you are dealing with a world as large as that, I believe it pays to have this tool generate individual images for each chunk. Then slap on an html/javascript front-end which loads each chunk image on request. Something like a Google Maps interface, but without the zoom capabilities. This will make it infinitely easier for your users to browse through the map and will not cause programs to throw a fit over the enourmous PNG size :)

To make it more interesting, instead of having Zoom capabilities, use a 'Zoom' slider to cycle through time! You stated you made new snapshots every day. Save them all, so you can see the world evolving right in front of you just be moving the slider around.

**Comment by dopeghoti** [comment]
I'd love to do this, when I have the time to throw at it.  That is in fact why I've been saving daily snapshots.

My images cache is now taking up 25GiB.

**Comment by kmpm** [comment]
Issue #15 is somewhat related to this.
