### ISSUE TITLE
Final PNG libpng error

### ISSUE THREAD

**Issue by PeterN** [spoutn1k/mcmap#4]
Compiled 2011-02-26 18:00 GMT on a Debian Lenny system.

Last set of messages from the output...

Pass 16 of 16...
Creating temporary image: 4032x2275, 32bpp, 34.99MiB
Terrain takes up 130.03MiB
Loading all chunks..
[0.00%]
[100.00%]
Optimizing terrain...
[0.00%]
[22.24%]
[40.66%]
[73.31%]
[87.59%]
[99.61%]
[100.00%]
Drawing map...
[0.00%]
[100.00%]
Composing final png file...
[0.00%]
libpng error: png_write_info was never called before png_write_row.
Job complete.

**Comment by bashtech** [comment]
Having same issue as well. 

Composing final png file...
[0.00%]
libpng error: png_write_info was never called before png_write_row.
Job complete.

**Comment by craze** [comment]
Apparently related to the new McRegion format.

I too got the error described above when I ran mcmap on a 1.3 world, but on an old world folder mcmap still ran as expected.

(FreeBSD 6.3-STABLE)

**Comment by Zahl** [comment]
Thanks for the report and sorry for not replying earlier. There was a problem with my mailbox; in the past few days, I received no emails anymore.

I'm currently still working on rendering and cropping and will partially switch back to the old way of doing it, since the current way wastes too much mem. While doing so, I will also take care of this issue, which has to do with disk caching.
