### ISSUE TITLE
Feature Request: Pin Markers

### ISSUE THREAD

**Issue by devyn** [spoutn1k/mcmap#8]
It'd be nice to be able to specify one or more points using the in-world (X,Z) coordinate system, and have mcmap generate 'pins' at those locations à la Google Maps.

This could be used, for example, to show the current saved location / spawn point of the player.

**Comment by Zahl** [comment]
This could be done relatively easy by automatically creating e.g. a red pile at the player's location, and a green one at spawn. Wouldn't be too pretty, but should work.
Adding a real (bitmap-)marker could lead to problems when using disk caching and would need more work.

**Comment by devyn** [comment]
A real marker graphic isn't necessary, I'm more worried about the ability to specify actual world coordinates (being able to place as many “pins” as you want, arbitrarily, if you so choose).

Of course, that would be nice too — options for spawn point / current position, that is.

**Comment by Zahl** [comment]
I added a very simple solution just now. It's not too pretty but I hope it helps.
Just add -marker c x z to the command line to get a marker at the specified x;z coordinate. c is the color and can be r, g, b or w. You can add this parameter multiple times to add more markers.
Since I'm more or less working on google maps output, I hope that I can provide a prettier/proper marker solution for that once it's done.
